"""change id to UUID

Revision ID: e17081ec645f
Revises: bd33b91e5355
Create Date: 2025-01-17 13:18:41.743126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e17081ec645f'
down_revision: Union[str, None] = 'bd33b91e5355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users ALTER COLUMN id TYPE UUID USING id::uuid;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
            existing_type=sa.UUID(),
            type_=sa.VARCHAR(),
            existing_nullable=False)
    # ### end Alembic commands ###
